from __future__ import annotations

import os

MAGIC = 0x58465448
ABI_VERSION = 2
HEADER_BYTES = 4096
SAMPLE_RATE = 44_100
CHANNELS = 2
DEFAULT_SOURCES = 4
MAX_SOURCES = 6
SOURCES = DEFAULT_SOURCES  # Synthetic IPC worker compatibility.
MAX_FRAMES = 257_985
SLOT_COUNT = 2


def align64(value: int) -> int:
    return (value + 63) & ~63


INPUT_SLOT_BYTES = CHANNELS * MAX_FRAMES * 4
OUTPUT_SLOT_BYTES = MAX_SOURCES * CHANNELS * MAX_FRAMES * 4
INPUT_SLOT_STRIDE = align64(INPUT_SLOT_BYTES)
OUTPUT_SLOT_STRIDE = align64(OUTPUT_SLOT_BYTES)
INPUT_BASE_OFFSET = HEADER_BYTES
OUTPUT_BASE_OFFSET = INPUT_BASE_OFFSET + SLOT_COUNT * INPUT_SLOT_STRIDE
TOTAL_BYTES = OUTPUT_BASE_OFFSET + SLOT_COUNT * OUTPUT_SLOT_STRIDE

STATE_INIT = 0
STATE_LAUNCHING = 1
STATE_READY = 2
STATE_PROCESSING = 3
STATE_ERROR = 4
STATE_STOPPED = 5
STATE_LOADING = 6
STATE_WARMING = 7
STATE_PRIMING = 8
STATE_RECOVERING = 9

COMMAND_NONE = 0
COMMAND_PROCESS = 1
COMMAND_RESET = 2
COMMAND_SHUTDOWN = 3

OFF_MAGIC = 0
OFF_ABI_VERSION = 4
OFF_HEADER_BYTES = 8
OFF_TOTAL_BYTES = 12
OFF_SAMPLE_RATE = 16
OFF_CHANNELS = 20
OFF_SOURCES = 24
OFF_MAX_FRAMES = 28
OFF_EPOCH = 32
OFF_REQUEST_SEQUENCE = 40
OFF_RESPONSE_SEQUENCE = 48
OFF_HEARTBEAT_COUNTER = 56
OFF_HEARTBEAT_MONOTONIC_MS = 64
OFF_STATE = 72
OFF_COMMAND = 76
OFF_ACTIVE_SLOT = 80
OFF_VALID_FRAMES = 84
OFF_STATUS_CODE = 88
OFF_INPUT_CHECKSUM = 96
OFF_OUTPUT_CHECKSUM = 104
OFF_INPUT_SLOT_STRIDE = 112
OFF_OUTPUT_SLOT_STRIDE = 116
OFF_INPUT_BASE_OFFSET = 120
OFF_OUTPUT_BASE_OFFSET = 124
OFF_CLIENT_PID = 128
OFF_WORKER_PID = 132
OFF_RESETS_COMPLETED = 136
OFF_PROCESSES_COMPLETED = 144
OFF_PROTOCOL_ERRORS = 152
OFF_WORKER_HANDLE_START = 160
OFF_WORKER_HANDLE_END = 164
OFF_LAST_ERROR = 168
LAST_ERROR_BYTES = 512
OFF_LAST_INFERENCE_US = 680
OFF_CUDA_ALLOCATED_BYTES = 688
OFF_CUDA_RESERVED_BYTES = 696
OFF_CUDA_MAX_ALLOCATED_BYTES = 704
OFF_CUDA_MAX_RESERVED_BYTES = 712
OFF_CUDA_DEVICE_INDEX = 720
OFF_GPU_NAME = 728
GPU_NAME_BYTES = 128
OFF_SEGMENT_FRAMES = 856
OFF_HOP_FRAMES = 860
OFF_COMPUTE_BACKEND = 864
OFF_REQUESTED_BACKEND = 868
OFF_MODEL_NAME = 872
MODEL_NAME_BYTES = 64

BACKEND_AUTO = 0
BACKEND_CUDA = 1
BACKEND_CPU = 2
BACKEND_MPS = 3


def mapping_name(session: str) -> str:
    if os.name == "nt":
        return rf"Local\{session}_shm"
    return f"/{session}_m"


def event_name(session: str, suffix: str) -> str:
    if os.name == "nt":
        return rf"Local\{session}_{suffix}"
    suffixes = {"request": "q", "response": "p", "ready": "y", "shutdown": "s"}
    return f"/{session}_{suffixes[suffix]}"


assert INPUT_SLOT_STRIDE == 2_063_936
assert OUTPUT_SLOT_STRIDE == 12_383_296
assert OUTPUT_BASE_OFFSET == 4_131_968
assert TOTAL_BYTES == 28_898_560
